language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - pytest
  - coverage run --source=iReporterAPI test_iReporterApi.py test
  - nosetests
after_success:
  - COVERALLS_REPO_TOKEN=BLX8M9VNcKdisRvlSQxKN3xbWr1UVCG57 coveralls
  - coveralls