language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - pytest --cov=asimwec/iReporterAPI
  - coverage run test_iReporterApi.py test
  - nosetests --cov=asimwec/iReporterAPI
after_success:
  - coveralls